Multi-Linear Regression

Importing Libraries

In [28]:
import pandas as pd
import numpy as np
from sklearn import linear_model

Importing data

In [29]:
df = pd.read_csv('house_prices.csv')
df

     area  bedrooms  age   price
0    3974       5.0   29  663000
1    1660       2.0   13  301700
2    2094       3.0   46  331700
3    1930       3.0   35  329300
4    1895       4.0    6  315600
..    ...       ...  ...     ...
245  1093       1.0   22  214100
246  3127       4.0   21  552100
247  3731       5.0    6  655700
248   997       2.0    6  288200
249  3829       5.0   48  631800

[250 rows x 4 columns]

Exploring Data

In [30]:
df.shape

(250, 4)

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.isnull().sum()

area         0
bedrooms    28
age          0
price        0
dtype: int64

In [33]:
df.describe()

              area    bedrooms        age          price
count   250.000000  222.000000  250.00000     250.000000
mean   2457.492000    3.554054   25.40800  437756.800000
std     897.197225    1.284878   14.78336  152172.632276
min     801.000000    1.000000    1.00000  128000.000000
25%    1756.250000    2.250000   13.00000  310050.000000
50%    2414.000000    4.000000   25.50000  428350.000000
75%    3232.750000    5.000000   38.00000  568775.000000
max    3984.000000    5.000000   50.00000  726500.000000

Fixing missing data using median

In [34]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [35]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

     area  bedrooms  age   price
0    3974       5.0   29  663000
1    1660       2.0   13  301700
2    2094       3.0   46  331700
3    1930       3.0   35  329300
4    1895       4.0    6  315600
..    ...       ...  ...     ...
245  1093       1.0   22  214100
246  3127       4.0   21  552100
247  3731       5.0    6  655700
248   997       2.0    6  288200
249  3829       5.0   48  631800

[250 rows x 4 columns]

In [36]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

Using Linear Regression

In [37]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [38]:
reg.coef_

array([  153.84499218,  6933.72008286, -1297.71912436])

In [39]:
reg.intercept_

np.float64(67667.2828001235)

In [40]:
reg.predict([[3000,3,40]])

c:\Users\boogey\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498094.6546272])

In [41]:
df_t = pd.read_csv('test_house_prices.csv')
df_t

    area  bedrooms  age
0    950       2.0   15
1   1400       3.0    8
2   1750       3.0   25
3   2100       4.0   30
4   2450       4.0    5
5   2800       4.0   12
6   3150       5.0   45
7   3500       5.0    2
8   1100       2.0   40
9   1950       3.0   18
10  2600       4.0   10
11  3300       5.0   22
12  1600       NaN   14
13  2250       4.0    3
14  3800       5.0   50

In [43]:
df_t.isnull().sum()

area        0
bedrooms    1
age         0
dtype: int64

In [44]:
median_bedrooms = math.floor(df_t.bedrooms.median())
median_bedrooms

4

In [45]:
df_t.bedrooms = df_t.bedrooms.fillna(median_bedrooms)
df_t

    area  bedrooms  age
0    950       2.0   15
1   1400       3.0    8
2   1750       3.0   25
3   2100       4.0   30
4   2450       4.0    5
5   2800       4.0   12
6   3150       5.0   45
7   3500       5.0    2
8   1100       2.0   40
9   1950       3.0   18
10  2600       4.0   10
11  3300       5.0   22
12  1600       4.0   14
13  2250       4.0    3
14  3800       5.0   50

In [46]:
reg.predict(df_t)

array([208221.67867552, 293469.67911186, 325254.20126222, 379545.07298779,
       465833.79836133, 510595.51175532, 528550.24799876, 638197.91761081,
       198855.44939414, 365107.23356962, 482421.95156718, 581474.53668672,
       323386.08288541, 437660.23817319, 622060.89729676])

In [47]:
p = reg.predict(df_t)

In [49]:
df_t['predicted prices']= p
df_t

    area  bedrooms  age  predicted prices
0    950       2.0   15     208221.678676
1   1400       3.0    8     293469.679112
2   1750       3.0   25     325254.201262
3   2100       4.0   30     379545.072988
4   2450       4.0    5     465833.798361
5   2800       4.0   12     510595.511755
6   3150       5.0   45     528550.247999
7   3500       5.0    2     638197.917611
8   1100       2.0   40     198855.449394
9   1950       3.0   18     365107.233570
10  2600       4.0   10     482421.951567
11  3300       5.0   22     581474.536687
12  1600       4.0   14     323386.082885
13  2250       4.0    3     437660.238173
14  3800       5.0   50     622060.897297

In [50]:
df_t.to_csv("Predicted.csv")

Done