In [1]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [3]:
import pandas as pd
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

    sepal length (cm)  sepal width (cm)  ...  petal width (cm)      flower
47                4.6               3.2  ...               0.2      setosa
48                5.3               3.7  ...               0.2      setosa
49                5.0               3.3  ...               0.2      setosa
50                7.0               3.2  ...               1.4  versicolor
51                6.4               3.2  ...               1.5  versicolor

[5 rows x 5 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [7]:
model = svm.SVC(kernel='rbf', C=3, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9777777777777777

In [10]:
from sklearn.model_selection import cross_val_score

In [13]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [12]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [14]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [17]:
Kernels = ['linear', 'poly', 'rbf', 'sigmoid']
C = [1, 10, 20, 30, 40, 50]
avg_score = {}
for kval in Kernels:
    for cval in C:
        cv_score = cross_val_score(
            svm.SVC(kernel=kval, C=cval, gamma='auto'),
            iris.data,
            iris.target,
            cv=5
        )
        avg_score[f'{kval}_{cval}'] = cv_score.mean()

avg_scores = avg_score
avg_scores

{'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666),
 'linear_30': np.float64(0.96),
 'linear_40': np.float64(0.96),
 'linear_50': np.float64(0.9666666666666666),
 'poly_1': np.float64(0.9666666666666666),
 'poly_10': np.float64(0.9666666666666666),
 'poly_20': np.float64(0.9533333333333334),
 'poly_30': np.float64(0.9533333333333334),
 'poly_40': np.float64(0.9533333333333334),
 'poly_50': np.float64(0.96),
 'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'rbf_30': np.float64(0.96),
 'rbf_40': np.float64(0.96),
 'rbf_50': np.float64(0.96),
 'sigmoid_1': np.float64(0.09333333333333334),
 'sigmoid_10': np.float64(0.09333333333333334),
 'sigmoid_20': np.float64(0.09333333333333334),
 'sigmoid_30': np.float64(0.09333333333333334),
 'sigmoid_40': np.float64(0.09333333333333334),
 'sigmoid_50': np.float64(0.09333333333333334)}

Using Grid search CV

In [21]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20, 30, 40, 50],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.0060915 , 0.00471044, 0.00457678, 0.00798197, 0.00272632,
        0.00811563, 0.00323148, 0.00433936, 0.00251493, 0.01162496,
        0.00269542, 0.00449996, 0.00291414, 0.01233964, 0.00333323,
        0.00328612, 0.00252719, 0.01452799, 0.00400271, 0.00575476,
        0.0053268 , 0.01873469, 0.0031805 , 0.00478654]),
 'std_fit_time': array([0.00308722, 0.00191079, 0.00169604, 0.00298349, 0.00091806,
        0.00472252, 0.00102956, 0.00188338, 0.00121719, 0.00837828,
        0.00036956, 0.00129755, 0.00117821, 0.00723072, 0.00185671,
        0.00068036, 0.00136511, 0.00638559, 0.00193467, 0.00286479,
        0.00360445, 0.01139396, 0.00076637, 0.00159849]),
 'mean_score_time': array([0.0052218 , 0.00253491, 0.00225153, 0.00312114, 0.00206323,
        0.00149722, 0.00306182, 0.00187688, 0.00130105, 0.00157666,
        0.00248642, 0.00192385, 0.00186667, 0.00147696, 0.00164723,
        0.00247149, 0.00152922, 0.00341287, 0.00237975, 0.00529618,
        0.00255423, 0.00298123, 0.00283027, 0.00245824]),
 'std_score_time': array([0.00445658, 0.00082344, 0.00045991, 0.00132192, 0.00111515,
        0.00019809, 0.00058417, 0.0006605 , 0.00022724, 0.00048271,
        0.00123995, 0.00028592, 0.00070884, 0.00030088, 0.00050466,
        0.00152162, 0.00077749, 0.00190856, 0.00109592, 0.00460246,
        0.00206712, 0.00112667, 0.00147668, 0.00067921]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20, 30, 30, 30,
                    30, 40, 40, 40, 40, 50, 50, 50, 50],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'poly'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'sigmoid'},
  {'C': 40, 'kernel': 'linear'},
  {'C': 40, 'kernel': 'poly'},
  {'C': 40, 'kernel': 'rbf'},
  {'C': 40, 'kernel': 'sigmoid'},
  {'C': 50, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'poly'},
  {'C': 50, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 0.33333333, 1.        ,
        1.        , 0.96666667, 0.33333333, 1.        , 0.96666667,
        0.96666667, 0.33333333, 1.        , 0.96666667, 0.96666667,
        0.33333333, 1.        , 0.96666667, 1.        , 0.33333333,
        1.        , 0.96666667, 1.        , 0.33333333]),
 'split1_test_score': array([1.        , 1.        , 1.        , 0.1       , 1.        ,
        1.        , 1.        , 0.1       , 1.        , 0.96666667,
        1.        , 0.1       , 1.        , 0.96666667, 1.        ,
        0.1       , 1.        , 0.96666667, 0.96666667, 0.1       ,
        1.        , 0.96666667, 0.96666667, 0.1       ]),
 'split2_test_score': array([0.96666667, 0.9       , 0.96666667, 0.        , 0.9       ,
        0.9       , 0.96666667, 0.        , 0.9       , 0.9       ,
        0.9       , 0.        , 0.9       , 0.9       , 0.9       ,
        0.        , 0.9       , 0.9       , 0.9       , 0.        ,
        0.9       , 0.93333333, 0.9       , 0.        ]),
 'split3_test_score': array([0.96666667, 0.93333333, 0.96666667, 0.03333333, 0.96666667,
        0.93333333, 0.96666667, 0.03333333, 0.93333333, 0.93333333,
        0.96666667, 0.03333333, 0.9       , 0.93333333, 0.93333333,
        0.03333333, 0.9       , 0.93333333, 0.93333333, 0.03333333,
        0.93333333, 0.93333333, 0.93333333, 0.03333333]),
 'split4_test_score': array([1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
        1., 1., 0., 1., 1., 1., 0.]),
 'mean_test_score': array([0.98      , 0.96666667, 0.98      , 0.09333333, 0.97333333,
        0.96666667, 0.98      , 0.09333333, 0.96666667, 0.95333333,
        0.96666667, 0.09333333, 0.96      , 0.95333333, 0.96      ,
        0.09333333, 0.96      , 0.95333333, 0.96      , 0.09333333,
        0.96666667, 0.96      , 0.96      , 0.09333333]),
 'std_test_score': array([0.01632993, 0.0421637 , 0.01632993, 0.12543258, 0.03887301,
        0.0421637 , 0.01632993, 0.12543258, 0.0421637 , 0.03399346,
        0.03651484, 0.12543258, 0.04898979, 0.03399346, 0.03887301,
        0.12543258, 0.04898979, 0.03399346, 0.03887301, 0.12543258,
        0.0421637 , 0.02494438, 0.03887301, 0.12543258]),
 'rank_test_score': array([ 1,  6,  1, 19,  4,  6,  1, 19,  6, 16,  5, 19, 10, 16, 10, 19, 10,
        16, 10, 19,  6, 10, 10, 19], dtype=int32)}

In [22]:
df = pd.DataFrame(clf.cv_results_)
df

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0        0.006091      0.003087  ...        0.016330                1
1        0.004710      0.001911  ...        0.042164                6
2        0.004577      0.001696  ...        0.016330                1
3        0.007982      0.002983  ...        0.125433               19
4        0.002726      0.000918  ...        0.038873                4
5        0.008116      0.004723  ...        0.042164                6
6        0.003231      0.001030  ...        0.016330                1
7        0.004339      0.001883  ...        0.125433               19
8        0.002515      0.001217  ...        0.042164                6
9        0.011625      0.008378  ...        0.033993               16
10       0.002695      0.000370  ...        0.036515                5
11       0.004500      0.001298  ...        0.125433               19
12       0.002914      0.001178  ...        0.048990               10
13       0.012340      0.007231  ...        0.033993               16
14       0.003333      0.001857  ...        0.038873               10
15       0.003286      0.000680  ...        0.125433               19
16       0.002527      0.001365  ...        0.048990               10
17       0.014528      0.006386  ...        0.033993               16
18       0.004003      0.001935  ...        0.038873               10
19       0.005755      0.002865  ...        0.125433               19
20       0.005327      0.003604  ...        0.042164                6
21       0.018735      0.011394  ...        0.024944               10
22       0.003181      0.000766  ...        0.038873               10
23       0.004787      0.001598  ...        0.125433               19

[24 rows x 15 columns]

In [23]:
df[['param_C', 'param_kernel', 'mean_test_score', 'std_test_score', 'rank_test_score']].sort_values(by='rank_test_score')

    param_C param_kernel  mean_test_score  std_test_score  rank_test_score
0         1       linear         0.980000        0.016330                1
2         1          rbf         0.980000        0.016330                1
6        10          rbf         0.980000        0.016330                1
4        10       linear         0.973333        0.038873                4
10       20          rbf         0.966667        0.036515                5
5        10         poly         0.966667        0.042164                6
8        20       linear         0.966667        0.042164                6
1         1         poly         0.966667        0.042164                6
20       50       linear         0.966667        0.042164                6
14       30          rbf         0.960000        0.038873               10
16       40       linear         0.960000        0.048990               10
12       30       linear         0.960000        0.048990               10
18       40          rbf         0.960000        0.038873               10
21       50         poly         0.960000        0.024944               10
22       50          rbf         0.960000        0.038873               10
13       30         poly         0.953333        0.033993               16
9        20         poly         0.953333        0.033993               16
17       40         poly         0.953333        0.033993               16
3         1      sigmoid         0.093333        0.125433               19
7        10      sigmoid         0.093333        0.125433               19
15       30      sigmoid         0.093333        0.125433               19
11       20      sigmoid         0.093333        0.125433               19
19       40      sigmoid         0.093333        0.125433               19
23       50      sigmoid         0.093333        0.125433               19

In [24]:
clf.best_score_

np.float64(0.9800000000000001)

In [25]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [27]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20, 30, 40, 50],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']}, cv=5, return_train_score=False, n_iter=2)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score', 'std_test_score', 'rank_test_score']].sort_values(by='rank_test_score')

   param_C param_kernel  mean_test_score  std_test_score  rank_test_score
1        1       linear         0.980000        0.016330                1
0       40      sigmoid         0.093333        0.125433                2

choosing the best model

In [30]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [33]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', max_iter=1000),
        'params': {
            'C': [1, 5, 10]
        }
    }
}

In [35]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    if model_name == 'logistic_regression':
        clf.estimator.set_params(solver='lbfgs')

    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [37]:
df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

                 model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.973333                   {'C': 1}